# ISO 8583 Server
spring.application.name=ISO8583

# Aplicación Standalone
spring.main.web-application-type=none

# Puerto y host del servidor TCP ISO 8583
iso8583.server.port=9999
iso8583.server.host=localhost


# SQL Server Database Configuration (JdbcTemplate)
# Conexión a SQL Server (SQLEXPRESS en puerto 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ISO8583DB;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=iso_user
spring.datasource.password=IsoPassword123!

# Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.idle-timeout=300000


# Idempotencia (Almacenada en SQL Server con JdbcTemplate)
iso8583.idempotency.ttl-seconds=86400


# Rate Limiting
iso8583.rate-limit.max-requests=4
iso8583.rate-limit.window-seconds=60


# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.coreBanking.registerHealthIndicator=false
resilience4j.circuitbreaker.instances.coreBanking.failureRateThreshold=50
resilience4j.circuitbreaker.instances.coreBanking.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.coreBanking.slidingWindowSize=10
resilience4j.circuitbreaker.instances.coreBanking.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.coreBanking.permittedNumberOfCallsInHalfOpenState=3


# Logging
#logging.level.servidor.ISO8583=DEBUG
#logging.level.org.springframework.jdbc=INFO
logging.file.name=logs/iso8583-server.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7


logging.level.com.microsoft.sqlserver.jdbc.internals.TDS.Channel=ERROR
logging.level.com.zaxxer.hikari=WARN
